### ISSUE TITLE
There should be "show all" button in "Compare tools" and "Latest Project" sections

### ISSUE THREAD

**Issue by lenka21** [noisy-witness/steemprojects.com#12]
![selection_374](https://user-images.githubusercontent.com/201263/31849285-d3131d9e-b640-11e7-8d65-26c40aa75557.png)

buttons should redirect users to:

/grids/
/projects/

**Comment by noisy** [comment]
@andrejcibik should we just use normal button, smaller one, 

![selection_375](https://user-images.githubusercontent.com/201263/31849325-1200f562-b641-11e7-8eff-fa89f7f68238.png)

![selection_376](https://user-images.githubusercontent.com/201263/31849326-17e7b61e-b641-11e7-9ea5-8bdece19c740.png)

or you have another idea?

**Comment by andrejcibik** [comment]
I think small one might be enough. 
Will it expand the section and dynamicaly add new items or link somewhere else?

**Comment by noisy** [comment]
@andrejcibik 

> Will it expand the section and dynamicaly add new items or link somewhere else?

link elsewhere, to pages **which are not ready yet**:

* https://steemprojects.com/grids in case of "Comparision Tools" 

and 

* https://steemprojects.com/projects in case of "All projects"

**Comment by noisy** [comment]
currently, only redirection to https://steemprojects.com/projects/ is implemented:

![selection_999 026](https://user-images.githubusercontent.com/201263/44310536-458e0980-a3d8-11e8-9ab5-7247ab402465.png)
