### ISSUE TITLE
Proposal to choose a language when adding a new project

### ISSUE THREAD

**Issue by hodoolee** [noisy-witness/steemprojects.com#146]
Hey guys,

I thought it would be great if it has a field for choosing a language of the project when adding a new project. I am sure that there are many developers looking for projects by language for the contributions. I would love to hear some thoughts.

Thanks.

**Comment by noisy** [comment]
I think, this is a great idea. Some time ago I described how this could be implemented 

- [A User of a SteemProject should be able to find all projects written in his favorite language](https://github.com/noisy-witness/steemprojects.com/issues/37)

I will close this issue as a duplicate.
