### ISSUE TITLE
Introduce status/state field to project model

### ISSUE THREAD

**Issue by noisy** [noisy-witness/steemprojects.com#6]
Currently available statuses:

- Live/Released - Project is ready to use
- Working Prototype/Beta - Project is working however, it still can contain some bugs
- Demo/Alpha - Project can be used by people which are not afraid of bugs and has very high pain threshold
- Concept - Something that pretends to be a working project
- Abandoned/Broken - Project is no longer available or it is completely broken
- Out of Date/Retired - Project is no longer needed, because of changes in ecosystem

Description of each status will be displayed as help message in add_project. 

Also, I would like to add information about status, to project's page, with description of status as a help message.

**Comment by noisy** [comment]
@andrejcibik: do you have an idea, where this status field could be displayed on project's page?

**Comment by andrejcibik** [comment]
How about right after the title? 

![project-desc](https://user-images.githubusercontent.com/17384787/30001336-68a2d006-908b-11e7-9e76-feec2eebc14c.jpg)

**Comment by andrejcibik** [comment]
TOOTIP CSS: 

```
.tooltip {
	text-transform: none !important;
	font-weight: 400 !important;
	display: none;
	width: auto;
	text-align: center;
	line-height: 1.4;
	position: absolute;
	left: 50%;
	top: 60%;
	-webkit-transform: translate(-50%, 14px);
	-ms-transform: translate(-50%, 14px);
	transform: translate(-50%, 14px);
	max-width: 195px;
	background-color: #3e4f5e;
	border-radius: 1px;
	padding: 5px;
	color: #fff;
	font-size: 12px;
}
```

JS


```
// TOOLTIP +
  $('.tip').hover(function(){
      var title = $(this).attr('title');

			$(this).data('tipText', title).removeAttr('title');
      $('<span class="tooltip shadow-1"></span>')
      .text(title)
      .appendTo(this)
      .fadeIn('fast')
			.css('display','inline-block');
  }, function() {
				$(this).attr('title', $(this).data('tipText'));
        $('.tooltip').remove();
    });

	$('.tip').click(function(){
			$('.tooltip').remove();
	});
// TOOLTIP -
```

**Comment by noisy** [comment]
Statuses are already implemented
